### ISSUE TITLE
Не работает lensdata.json

### ISSUE THREAD

**Issue by Tuchanka** [mikhail-rodin/OpticGOST#2]
Здравствуйте, Михаил. Меня зовут Артем и я являюсь студентом 6 курса МГТУ им. Н.Э. Баумана. Возникла ошибка с файлом lensdata.json. В чем может быть проблема?
![Скриншот 2021-05-31 01 36 08](https://user-images.githubusercontent.com/84408239/120122405-335c6f00-c1b1-11eb-9ea5-42147683c2d0.png)
![Скриншот 2021-05-31 01 36 12](https://user-images.githubusercontent.com/84408239/120122416-3a837d00-c1b1-11eb-9a16-d6aa65b10737.png)
![Скриншот 2021-05-31 01 36 19](https://user-images.githubusercontent.com/84408239/120122417-3c4d4080-c1b1-11eb-8fff-5699b63eb988.png)

**Comment by mikhail-rodin** [comment]
Привет, коллега! На скринах старая версия надстройки, и притом ещё недоделанная: пытается открыть файл lensdata, предназначенный для отладки. 
Выложил в релизах актуальную версию 1.3.2. Там такого быть не должно.

**Comment by Tuchanka** [comment]
Добрый день! Огромное вам спасибо за проделанную работу, установил версию 1.3.2 и теперь lensdata.json строит таблицы аберраций. Успехов в дальнейшей работе!
![Скриншот 2021-05-31 16 33 25](https://user-images.githubusercontent.com/84408239/120201389-0ef2a800-c22e-11eb-9f8b-88cf2e0a47ca.png)
